notifications:
- mode: "ON"
- dest: "test@mail.com"

stopword: "stop"

reminder_patient: 
 minutes: "1"

reminder_end_session: 
 minutes: "1"

sessions:
 session1:
  begin: "2018,6,14,16,30,0"
  end: "2018,8,14,16,31,0"
  reminder_time:
   minutes: "1"
  requested_slot: 
   pain: "pain_level,body_part,pain_duration,pain_change"
   sport: "sport,sport_duration"
