follow_in_current_session_plus: 1
reminder_end_session:
  minutes: '1'
reminder_patient:
  minutes: '1'
reminder_patient_little:
  minutes: '1'
sessions:
  1:
    begin: 2018,6,21,16,39,0
    end: 2018,6,21,16,42,0
    followed_intent: emotional_sadness
    reminder_time:
      minutes: '1'
    requested_intent: pain,activity
    requested_slot:
      pain: pain_desc,body_part,pain_duration,pain_change
      sport: sport,sport_duration
  2:
    begin: 2018,6,21,16,42,1
    end: 2018,6,21,16,45,0
    followed_intent: emotional_sadness
    reminder_time:
      minutes: '1'
    requested_intent: pain,activity
    requested_slot:
      pain: pain_desc,body_part,pain_duration,pain_change
      sport: sport,sport_duration
stopword: stop
emergency : help
nickname : Ailixir
exit : gone
