follow_in_current_session_plus: 1
reminder_end_session:
  minutes: '1'
reminder_patient:
  minutes: '1'
reminder_patient_little:
  minutes: '1'
sessions:
  1:
    begin: 2018,6,22,14,49,0
    end: 2018,6,22,14,51,0
    followed_intent: None
    requested_intent: None
    requested_slot: None
  2:
    begin: 2018,6,22,14,51,1
    end: 2018,6,22,14,53,0
    followed_intent: emotional_sadness
    requested_intent: pain,activity
    requested_slot:
      pain: pain_desc,body_part,pain_duration,pain_change
      activity: sport,sport_duration,activity_hard
stopword: stop
emergency : help
nickname : Ailixir
exit : gone
count_user_reminder_max : 1
