language: "fr"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "intent_featurizer_ngrams"
  max_number_of_ngrams: 2
- name: "ner_duckling_http"
  url: "http://0.0.0.0:8000"
  dimensions: ["time", "distance", "duration", "temperature"]
- name: "intent_classifier_sklearn"
