language: 'en'
follow_in_current_session_plus: 1
reminder_end_session:
  minutes: '1'
reminder_patient:
  minutes: '1'
reminder_patient_little:
  minutes: '1'
sessions:
  1:
    duration:
      minutes: '15'
    followed_intent: None
    requested_intent: treatment,infoPatient
    requested_slot:
      treatment: medicinal,treatment_being_taken,drug,treatment_ok,dosing,treatment_time,treatment_overdosage,treatment_prescripted,treatment_period
      infoPatient: weight,infoPatient_time,infoPatient_distance,infoPatient_temperature,gender,heart_rate,blood_pressure

  2:
    duration:
      minutes: '3'
    followed_intent: None
    requested_intent: pain
    requested_slot:
      pain: pain_desc
      activity: sport,activity_distance
  3:
    duration:
      minutes: '5'
    followed_intent: None
    requested_intent: pain
    requested_slot:
      pain: pain_desc
      activity: sport,activity_distance
stopword: stop
emergency : help
nickname : Ailixir
exit : gone
count_user_reminder_max : 1


