language: 'FRA'
follow_in_current_session_plus: 1
reminder_end_session:
  minutes: '1'
reminder_patient:
  minutes: '1'
reminder_patient_little:
  minutes: '1'
sessions:
  1:
    duration:
      minutes: '15'
    followed_intent: None
    requested_intent: treatment,infoPatient,activity,pain,pathology,social,positiveEmo,negativeEmo,sleep,eatingDisorders,drugAddiction,smoking,alcohol
    requested_slot:
      treatment: treatment_medicinal,treatment_being_taken,treatment_drug,treatment_ok,treatment_dosing,treatment_time,treatment_overdosage,treatment_prescripted,treatment_period,treatment_duration
      infoPatient: infoPatient_weight,infoPatient_time,infoPatient_distance,infoPatient_temperature,infoPatient_gender,infoPatient_heart_rate,infoPatient_blood_pressure,infoPatient_addiction
      activity: activity_sport,activity_duration,activity_period,activity_distance,activity_hard,activity_time
      pain: pain_duration,pain_desc,pain_body_part,pain_period,pain_time,pain_change
      pathology: pathology_symptom,pathology_time,pathology_period,pathology_body_part,pathology_change,pathology_treatment_linked,pathology_duration
      sleep: sleep_duration,sleep_quality
      eatingDisorders: eatingDisorders_time,eatingDisorders_duration
      drugAddiction: drugAddiction_period,drugAddiction_drug,drugAddiction_dosing,drugAddiction_duration,drugAddiction_time
      smoking: smoking_period,smoking_dosing,smoking_duration,smoking_time
      alcohol: alcohol_period,alcohol_dosing,alcohol_duration,alcohol_time

  2:
    duration:
      minutes: '3'
    followed_intent: None
    requested_intent: pain
    requested_slot:
      pain: pain_desc
      activity: activity_sport,activity_distance
  3:
    duration:
      minutes: '5'
    followed_intent: None
    requested_intent: pain
    requested_slot:
      pain: pain_desc
      activity: activity_sport,activity_distance
stopword: stop
emergency : help
nickname : Ailixir
exit : gone
count_user_reminder_max : 1


