follow_in_current_session_plus: 1
reminder_end_session:
  minutes: '1'
reminder_patient:
  minutes: '1'
reminder_patient_little:
  minutes: '1'
sessions:
  1:
    begin: 2018,6,26,15,35,1
    end: 2018,6,26,16,12,0
    followed_intent: emotional_sadness, social
    requested_intent: pain,activity
    requested_slot:
      pain: pain_desc,body_part,pain_duration,pain_change
      activity: sport,sport_duration,activity_hard
  2:
    begin: 2018,6,26,16,12,1
    end: 2018,6,26,16,14,0
    followed_intent: emotional_sadness, social
    requested_intent: pain,activity
    requested_slot:
      pain: pain_desc,body_part,pain_duration,pain_change
      activity: sport,sport_duration,activity_hard
  3:
    begin: 2018,6,26,16,14,1
    end: 2018,6,26,16,16,0
    followed_intent: emotional_sadness, social
    requested_intent: pain,activity
    requested_slot:
      pain: pain_desc,body_part,pain_duration,pain_change
      activity: sport,sport_duration,activity_hard
stopword: stop
emergency : help
nickname : Ailixir
exit : gone
count_user_reminder_max : 1
