language: 'fr'
follow_in_current_session_plus: 1
reminder_end_session:
  minutes: '1'
reminder_patient:
  minutes: '1'
reminder_patient_little:
  minutes: '1'
sessions:
  1:
    duration:
      minutes: '15'
    followed_intent: activity
    requested_intent: pain
    requested_slot:
      pain: pain_desc
      activity: sport,activity_distance
stopword: stop
emergency : help
nickname : Ailixir
exit : gone
count_user_reminder_max : 1
