language: 'en'
follow_in_current_session_plus: 1
reminder_end_session:
  minutes: '1'
reminder_patient:
  minutes: '1'
reminder_patient_little:
  minutes: '1'
sessions:
  1:
    begin: 2018,6,1,8,0,0
    end: 2018,10,1,7,59,59
    followed_intent: emotional_sadness,social
    requested_intent: pain,activity,pathology,treatment,infoPatient
    requested_slot:
      pain: pain_desc,pain_body_part,pain_duration,pain_change,pain_time,pain_period
      activity: sport,activity_duration,activity_hard,activity_time,activity_period,activity_distance
      pathology: symtoms,pathology_body_part
      treatment: medicinal,drug
      infoPatient: weight,infoPatient_distance,heart_rate,temperature,gender,blood_pressure,addiction,infoPatient_time
stopword: stop
emergency : help
nickname : Ailixir
exit : gone
count_user_reminder_max : 1
