language: 'fr'
follow_in_current_session_plus: 1
reminder_end_session:
  minutes: '1'
reminder_patient:
  minutes: '1'
reminder_patient_little:
  minutes: '1'
sessions:
  1:
    duration:
      minutes: '15'
    followed_intent: None
    requested_intent: None
    requested_slot:
      pathology: symtoms,pathology_body_part,pathology_time,pathology_change,pathology_period,pathology_treatment_linked
  2:
    duration:
      minutes: '3'
    followed_intent: None
    requested_intent: pain
    requested_slot:
      pain: pain_desc
      activity: sport,activity_distance
  3:
    duration:
      minutes: '5'
    followed_intent: None
    requested_intent: pain
    requested_slot:
      pain: pain_desc
      activity: sport,activity_distance
stopword: stop
emergency : help
nickname : Ailixir
exit : gone
count_user_reminder_max : 1
